name: sql injection PUT

on: [push]
  # push:
  #   # Action is called when a branch is merged with development
  #   branches:
  #     - development  

# env:
#   NODE_VERSION: '14'  # the version of node we are using
#   NPM_CONFIG_PREFIX: "~/.npm-global" # Required to set path for artillery call

jobs:
  PUT-sql-injection:
    # Create ubuntu VM for actions
    runs-on: ubuntu-latest 

    steps:
    #Checkout current repo
    - name: 'Checkout Repository GitHub Action' 
      uses: actions/checkout@v2

    - name: 'GET Request'
      uses: satak/webrequest-action@master
      with:
        url: https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1/tasks/3103
        method: GET
    
    - name: 'Create Task'
      run: |
        curl -v -X POST -d '{"title": "AlexTest","description": "Review and alter as needed"}' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1/tasks
  
    - name: 'SQL Injection'
      run: |
        curl -v -X PUT -d '{"title": "AlexTest","description": "Review and alter as needed"}' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1/tasks
  
    # - name: 'POST Request'
    #   uses: satak/webrequest-action@master
    #   with:
    #     url: https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1/tasks/
    #     method: POST
    #     payload: '{"title": "Actions test","description": "Test POST via github actions"}'


    # - name: 'PUT Request'

      uses: satak/webrequest-action@master
      with:
        url: https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1/tasks/3102
        method: PUT
        payload: '{
                    "title": "Alterations",
                    "description": SQL Injection’; DROP TABLE userId,
                    "createdDate": "2021-03-03 02:22:06.450000",
                    "completed": 1,
                    "completedDate": null
                  }'


name: sql injection PUT

on: [push]
  # push:
  #   # Action is called when a branch is merged with development
  #   branches:
  #     - development  

# env:
#   NODE_VERSION: '14'  # the version of node we are using
#   NPM_CONFIG_PREFIX: "~/.npm-global" # Required to set path for artillery call

jobs:
  PUT-sql-injection:
    # Create ubuntu VM for actions
    runs-on: ubuntu-latest 

    steps:
    #Checkout current repo
    - name: 'Checkout Repository GitHub Action' 
      uses: actions/checkout@v2

    - name: 'GET Request'
      uses: satak/webrequest-action@master
      with:
        url: https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1/tasks/3103
        method: GET

    - name: 'SQL Injection'
      run: |
        curl -v -X PUT -d '{
                            "title": "Alterations",
                            "description": SQL Injection’; DROP TABLE userId,
                            "createdDate": "2021-03-03 02:22:06.450000",
                            "completed": 1,
                            "completedDate": null
                           }' https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1/tasks/3103
  


 

 